format_version: 13
step_bundles:
  cached-xcode-archive:
    envs:
    - PROFILES_PATH_OLD: /Users/vagrant/Library/MobileDevice/Provisioning Profiles
    - PROFILES_PATH: /Users/vagrant/Library/Developer/Xcode/UserData/Provisioning Profiles
    steps:
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            set -o pipefail
            set -x
            mkdir -p "$PROFILES_PATH"
            mkdir -p "$PROFILES_PATH_OLD"
    - restore-cache:
        run_if: '{{enveq "USE_CACHED_PROVISIONING_PROFILES" "true"}}'
        inputs:
        - key: |-
            profile-cache-key-{{ checksum "$PROFILES_PATH_OLD/*.mobileprovision" }}-{{ checksum "$PROFILES_PATH/*.mobileprovision" }}
    - xcode-archive:
        inputs:
        - fallback_provisioning_profile_url_list: |-
            $PROFILES_PATH_OLD
            $PROFILES_PATH
        - automatic_code_signing: "api-key"
        - verbose_log: "yes"
    - save-cache:
        run_if: '{{enveq "USE_CACHED_PROVISIONING_PROFILES" "true"}}'
        inputs:
        - key: |-
            profile-cache-key-{{ checksum "$PROFILES_PATH_OLD/*.mobileprovision" }}-{{ checksum "$PROFILES_PATH/*.mobileprovision" }}
        - is_key_unique: 'true'
        - paths: |-
            $PROFILES_PATH_OLD
            $PROFILES_PATH